name: Sync to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Azure Storage
        uses: azure/actions/storage-sync@v1
        with:
          source_dir: dist # Path to your built files
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
